### ISSUE TITLE
Use normative language in profile expectations?

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/eat#100]
All the things in the profile are described as "should" right now.

If we are going to start using "must" then we are describing a formal protocol for creating profile documents to the degree that some profiles comply with EAT and some don't. That seems like an overreach and a tall order.

My leaning is to leave it as "should", but we can have a larger discussion about more formalism here. Maybe do this by filing a separate issue for it.

_Originally posted by @laurencelundblade in https://github.com/ietf-rats-wg/eat/pull/99#discussion_r594585117_

**Comment by gmandyam** [comment]
Closing issue as there has been no proposals, much less discussion on whether there should be any normative requirements for profile documents.  Moreover, as per Sec. 5.18 of https://datatracker.ietf.org/doc/draft-ietf-rats-eat/:

"There is no requirement that the named document be publicly accessible.  The primary purpose of the profile claim is to uniquely identify the profile even if it is a private profile."

It will be difficult to enforce normative requirements on a private profile.

In addition, in Sec.7:

"This EAT specification does not guarantee that implementations of it will interoperate. "
