### ISSUE TITLE
Add a recommendation that claim value should not be interdependent

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/eat#110]
It is probably better that every claim value stand on its own as much as possible. Claims should be designed this way. If some attribute or information about an entity needs several data items to describe it, it should be all in one claim rather than in several. This is to reduce interdependence between claims.

I'm not completely sure that is necessary, but it seems like a good idea.

**Comment by gmandyam** [comment]
I don't know whether this can work as general guidance.  Take for instance something like an app dependency declared in an Android manifest (i.e. intent).  If the attestable entity in question is that Android application, it would have to enumerate _all_ the attestable data from other entities (e.g. other Android applications) on which it has a dependency.  

On another note, I am not convinced that the current CoSWID spec (https://datatracker.ietf.org/doc/html/draft-ietf-sacm-coswid-16.txt) covers the notion of something like Android intents (or predecessors such as BREW extensions).  If I am correct in my interpretation, then this is a spec deficiency that should be fixed.

**Comment by laurencelundblade** [comment]
I don't want a prohibition against interdependency. It could occur if needed.

Here's an example of what I'd like to discourage -- one claim says what the format/type of another claim is. Instead, build the type/format determination into the claim like is done for the swevidence and manifests claim. It's pretty simple stuff.

I understand why a manifest for downloading SW needs to list needed dependencies and extensions, but I'm not sure that is necessary for attestation. That said, this is not a battle I'm going to go fight (have too much other work). I am mostly assuming the designers of CoSWID, CoMID and CoRIM know what they are doing.
