### ISSUE TITLE
Should minimum size of UEID be larger than 128 bits?

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/eat#12]
Ben commented that 128 bits is not enough. Is my analysis correct?

128 bits (16 bytes) is enough for one trillion humans to each have one trillion devices and the probability of collision less than a trillion (log base 10 of 2^ 128 = 38; log base 10 of a trillion is 12; 3 * 12 < 38) So 128 bits seems like enough, but take it out to 256 bits because SHA-256 is popular and good and there is some extra margin.

**Comment by nedmsmith** [comment]
Simply anticipating a namespace large enough to create a universally unique value doesn't ensure there will not be collisions. Often there is a namespace authority that applies a formula for testing uniqueness / collisions. This implies the namespace authority plays a role. For example, X.509 serial numbers are unique within the context of the issuing CA. The issuing CA is the namespace authority. The EUID definition implies namespace authorities exist for example the first 8 bytes of an IMEI identifies the mobile equipment vendor. Presumably the serial numbers are chosen by the vendor. 
It isn't clear that all EUIDs will have bits reserved for namespace authorities and that there will be some way to register them.

**Comment by laurencelundblade** [comment]
PR #35 includes a full probabilistic analysis rather than the poor one in my comment above.

@nedmsmith -- the draft proposes several types of UEIDs, some based on existing on device ID schemes guaranteed by a central database and one based purely on cryptographic quality large random numbers.

**Comment by laurencelundblade** [comment]
Fixed in #35
