### ISSUE TITLE
Early assignment for chip-version-scheme

### ISSUE THREAD

**Issue by dthaler** [ietf-rats-wg/eat#120]
TEEP needs early assignment for the chip-version-scheme claim but it's not listed in section 7.3.1

**Comment by gmandyam** [comment]
Is the request for IANA assignment of hw-version?  If so, I believe this is covered under https://github.com/ietf-rats-wg/eat/issues/131 and this issue can be closed as it is already being tracked separately.

**Comment by dthaler** [comment]
Closing since the draft now has TBD26
