### ISSUE TITLE
Add claims for non-nonce freshness

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/eat#136]
RATS architecture and other documents describe architecture for freshness that doesn't use a nonce. EAT should support them.

**Comment by gmandyam** [comment]
EAT builds upon CWT.  cwt id (https://datatracker.ietf.org/doc/html/rfc8392#section-3.1.7) can be used for ensuring replay protection.  In that regards, EAT supports two forms of replay protection.
