### ISSUE TITLE
Meet TEEP requirements for non-TEEP/SUIT specific claims

### ISSUE THREAD

**Issue by dthaler** [ietf-rats-wg/eat#138]
https://datatracker.ietf.org/doc/html/draft-ietf-teep-architecture#section-7 and 
https://datatracker.ietf.org/doc/html/draft-ietf-teep-protocol#section-4.3.1 have requirements to be able to somehow express, in some fashion (ideally not TEEP specific):

- [X] Device unique identifier - I think "ueid" meets this, if I understand correctly (and this was mentioned in the mailing list thread)
- [X] Vendor of the device - I think "oemid" can now do this
- [ ] Class of the device
- [X] TEE firmware type - I think "software-name" can now do this
- [X] TEE firmware version - I think "software-version" can now do this

https://datatracker.ietf.org/doc/draft-birkholz-rats-suit-claims/ proposed claims that are not TEEP/SUIT specific for all of the above:
* vendor-identifier, class-identifier, device-identifier, component-identifier, version

The TEEP protocol spec has a normative dependency on those, and we agreed they are not TEEP or SUIT specific.   This issue requests adding them, or some other way of expressing similar information, into the base EAT spec.  This has been discussed on the RATS mailing list and asked for in multiple past RATS meetings, so now tracking via this issue.

The latest version of draft-ietf-rats-eat added software-name and software-version which I believe are sufficient to meet the firmware type and version requirements, so this now just tracks anything remaining, which I think is just device class.

**Comment by dthaler** [comment]
Here's some of the discussion links, there are more (earlier ones) I can dig up later if needed:

* RATS email thread: https://mailarchive.ietf.org/arch/msg/rats/NRVt_SCZ7yH8M3SRbUZqlO448MY/
* Slides from IETF 111: https://datatracker.ietf.org/meeting/111/materials/slides-111-rats-sessc-rats-session-2-3-slide-bundle-03 slides 53-59
* Notes from IETF 111: https://notes.ietf.org/notes-ietf-111-rats

**Comment by dthaler** [comment]
The relevant part of draft-birkholz-rats-suit-claims that is not specific to SUIT or TEEP is:

> 3.1.  System Properties Claims
> 
>    System Properties Claims are composed of:
> 
>    *  Hardware Component Claims and
> 
>    *  Software Component Claims.
> 
>    Correspondingly, the Claim definitions below highlight if a Claim is
>    generic or hw/sw-component specific.
> 
> 3.1.1.  vendor-identifier
> 
>    A RFC 4122 UUID representing the vendor of the Attester or one of its
>    hardware and/or software components.
> 
>    $$system-property-claim //= ( vendor-identifier => RFC4122_UUID )
> 
> 3.1.2.  class-identifier
> 
>    A RFC 4122 UUID representing the class of the Attester or one of its
>    hardware and/or software components.
> 
>    $$system-property-claim //= ( class-identifier => RFC4122_UUID )
> 
> 3.1.3.  device-identifier
> 
>    A RFC 4122 UUID representing the Attester.
> 
>    $$system-property-claim //= ( device-identifier => RFC4122_UUID )
> 
> 3.1.4.  component-identifier
> 
>    A sequence of binary identifiers that is intended to identify a
>    software-component of an Attester uniquely.  A binary identifier can
>    represent a CoSWID [I-D.ietf-sacm-coswid] tag-id.
> 
>    $$system-property-claim //=  ( class-identifier => [ + identifier ] )
>

**Comment by bremoran** [comment]
From a SUIT perspective, many things can affect compatibility. Many software and hardware components can play a role. Some may even come from different vendors. We should not come under the illusion that a device has a single "oem." Devices may have a myriad of OEMs. Imagine a fleet tracking device that contains:

* An application processor
* A GPS module for obtaining location
* A WiFi module for when the vehicle is at a supported facility
* A LTE module for when the vehicle is in a city
* A Satellite communication module for when the vehicle is not in a city.

Why does it have so many communication interfaces? Because each one is more expensive to use than the previous.

Each of the modules has a separate vendor, hardware version, firmware version, and root of trust. The devices *as a whole* has an OEM, but so do each of the modules. Which OEM are you reporting? Is that good enough? Your device has a hierarchical structure, so your data should too.

**Comment by dthaler** [comment]
My understanding is that each claimset can have an oemid and describe a different component.  A device can have a set of claimsets, one per component, organized in a layered fashion, or a composite fashion.   As long as "oemid" can be used to hold a vendor id, then it's really a vendor id not an "OEM" id per se.   Someone please correct me if my understanding is incorrect.

Thanks,
Dave

**Comment by dthaler** [comment]
TEEP discussed this thread in the WG meeting this morning, where
many of the people who weighed in on the joint RATS/TEEP email thread were present
(thanks!)   Nancy did two polls during the meeting to get a sense
of the room.

My takeaway is that TEEP (with various participants from SUIT 
and RATS who weighed in) believes that RATS should define
a claim in the EAT spec, but leave the *values* to be defined by
profiles and by vendors (i.e., both categories are needed).
The TEEP profile would define values used by TEEP use cases,
as would other profiles.  Vendors would be able to define
vendor-specific values in addition to standard values defined in profiles.

Also TEEP had strong consensus that the values should be opaque
not structured.   As such, some believe a UUID would be better
than a byte blob or text string because a UUID helps ensure opaqueness,
but that’s for RATS to decide if RATS defines the claim and requirements
for profiles.

**Comment by laurencelundblade** [comment]
I believe this has been addressed by #139

**Comment by laurencelundblade** [comment]
Re opened this because through a conversation with Dave, it is clear that TEEP wants something that really is a class, not a model number.

**Comment by dthaler** [comment]
This was fixed so closing (can remote wontfix label but I don't have permissions to do that)
