### ISSUE TITLE
Identifying EAT objects

### ISSUE THREAD

**Issue by cyberphone** [ietf-rats-wg/eat#165]
Related issue: https://github.com/ietf-rats-wg/eat/issues/157
Related I-D: https://datatracker.ietf.org/doc/draft-ietf-cbor-file-magic/

A very active W3C group called Verified Credentials (VCs) are using attestations for delivering claims regarding individuals.  VC containers are identified as such by URLs featured in a dedicated JSON/JSON-LD property called @context (https://www.w3.org/TR/vc-data-model/#contexts).  When sent over HTTP, VCs use a static media type since the @context is supposed to tell the consumer what to expect.  This is similar to XML schemas and Namespaces.  Another W3C effort, PaymentRequest uses URLs (https://www.w3.org/TR/payment-request/#dom-paymentmethoddata-supportedmethods) for identifying custom payment handlers.

It is not entirely obvious how you translate this methodology to CBOR.  The following represents a concrete proposal intended to limit the need for multiple and over time probably diverging practices.  Since the scope of this issue is universal it is not limited to EAT. However, EAT represents a possible adopter.

## High Level Description

- CBOR data is enclosed by a _fixed_ top-level tag holding a URI or OID which are supposed to uniquely identify the "schema" (content specification) of the embedded data (payload).
- When such objects are transported over HTTP, the media type MUST be set to `application/cbor`.   That is, the proposed tag has _precedence_ over other possible media types associated with the payload.

<table><tr><td>Since objects using <i>self-contained type identifiers</i> are distinguishable from each other they can also be <i>embedded in other objects</i> in an interoperable and extensible way.</td></tr></table> 

If applied to https://datatracker.ietf.org/doc/html/draft-ietf-rats-eat-11 the following changes seem logical:
- 601() and similar application-specific tags would be replaced by the proposed construct.
- `profile-name` would be removed.

## In More Detail

TBD211([_Type Id_, _CBOR data_])

This CBOR tag extends major type 6 and presumes a 2-element array holding a type identifier and associated data.  For designs intended for external use, type identifiers are RECOMMENDED to be represented by `bstr` or `tstr` where `bstr` SHOULD be coded as _absolute_ OIDs according to RFC9090 while `tstr` SHOULD be coded as _absolute_ URLs, preferably pointing to a document describing the object.

The data (payload) portion of the tag is any valid CBOR object, only constrained by its specification given by the type identifier.

## Example

Assume that you have an object like
```code
{
  1: "Hello CBOR World!",
  2: Infinity
}
```
that is defined in a document located at `https://example.com/cbor-hello`.

After extending it with the proposed tag:
```code
TBD211(["https://example.com/cbor-hello", {
  1: "Hello CBOR World!",
  2: Infinity
}])
```

In binary/hex:
```code
D8 D3                                   # tag(211)
   82                                   # array(2)
      78 1E                             # text(30)
         68747470733A2F2F6578616D706C652E636F6D2F63626F722D68656C6C6F # "https://example.com/cbor-hello"
      A2                                # map(2)
         01                             # unsigned(1)
         71                             # text(17)
            48656C6C6F2043424F5220576F726C6421 # "Hello CBOR World!"
         02                             # unsigned(2)
         F9 7C00                        # primitive(31744)
```

## Parameterized Object Types
Although NOT RECOMMENDED, this specification does not "outlaw" parameterized type identifiers like the following:

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;TBD211([[_Main Type Id_, _Parameters_...], _CBOR data_])

However, in most real-world scenarios, an _extension scheme_ in the actual object is probably a better solution.

### Related Discussion
Anyway, whatever parameterization or extension scheme you use, it often comes with interoperability issues.   One way to combine extensions with a more agile ecosystem where not all object producers and consumers are at the same level, is making the latter announce their capabilities through _public discovery services_.  Then an object producer can determine what to send _before_ making a request, as well as concluding that the consumer isn't compatible with the producer's current requirements.

**Comment by gmandyam** [comment]
>When such objects are transported over HTTP, the media type MUST be set to application/cbor. That is, the proposed tag has precedence over other possible media types associated with the payload.

As per IETF 113 consensus decision, all normative references to UCCS will be removed.  Therefore transmission of an EAT as straight CBOR or JSON is not permitted going forward (exception being a token type DEB, which may or may not be included in the final RFC).  JWT and CWT media types would be more applicable along with their corresponding tags.
