### ISSUE TITLE
SHOULD or MUST re: cryptographic verifiability

### ISSUE THREAD

**Issue by carl-wallace** [ietf-rats-wg/eat#17]
This is possibly subsumed by issue 15. In section 1.2, why state "the attestation should be cryptographically verifiable by the EAT consumer"? Is the intent that some EAT consumers won't recognize the root of trust or that some EATs need not be cryptographically verifiable at all? If the former, maybe change from should to MUST and add qualifying words about root of trust for relying parties.

**Comment by nedmsmith** [comment]
Issue #23 seems to assert that claims are optional (except where Verifier policies make them mandatory). Issue #15 may have to do with how claims are packaged and attested (e.g. signed). It is possible for signing to take place at the data layer (aka via a signed manifest structure) or at a protocol layer (aka TLS). If the requirement for attestation is that claims MUST be signed. It seems there could be flexibility regarding what layer the signature is applied (protocol or data structure). It would not (likely) make sense to sign using the same key twice simply to satisfy normative that places the signing at the data structure layer.

**Comment by laurencelundblade** [comment]
Section 1.2 is intended as general introductory text to help the reader orient. 

My proposed solution here is to remove the "should" and generally soften into more descriptive language.

**Comment by gmandyam** [comment]
Have not seen a proposal on this issue.  In my opinion, the language "should be cryptographically verifiable" is also desirable as it can cover future use cases such as UCCS (unsigned EAT's).  Closing.
