### ISSUE TITLE
Use content or media type for Manifest and SWMeasurements

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/eat#177]
The idea in EAT is to carry formats like Coswid and Corim for Manifests and SWResults. A way to identify their type is needed. Right now CBOR tags are used, but MIME type or Coap content type is probably better.

**Comment by gmandyam** [comment]
Any proposal for new media types or subtypes should have a justification why the existing CWT media type is insufficient.  

If a subtype is being proposed for Corim/etc., then there should be a specific proposal and examples on how the subtypes are being conveyed.  I would suggest a POST example.

**Comment by laurencelundblade** [comment]
Fixed by #179
