### ISSUE TITLE
Multiple nonces in JSON

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/eat#180]
The CBOR definition of a nonce allows for multiple nonces to accommodate some of the more sophisticated use cases.

The JSON definition of a nonce is re used from the IANA JWT registry and doesn't allow multiple nonces.

**Comment by gmandyam** [comment]
Establish consensus within the group that multiple nonces are required, otherwise close.

**Comment by laurencelundblade** [comment]
Wasn't it you that wanted the multiple nonces?

Also something HAS to be fixed because it is inconsistent as is. Thus I've remove the wont fix.

**Comment by gmandyam** [comment]
>Wasn't it you that wanted the multiple nonces?

Not that I can recall.  If I did, then I would understand the use case.  Since we have disagreement among the editors, the proper place to raise this issue is on the list.

**Comment by gmandyam** [comment]
Until this is resolved on mailing list, restoring wontfix label.

**Comment by laurencelundblade** [comment]
Something has to be fixed here. It is not OK to have the CBOR nonce different from the JSON nonce.

Would appreciate us coming to consensus on wontfix before assign it. 

Removing wontfix.

**Comment by gmandyam** [comment]
I couldn't identify where in https://openid.net/specs/openid-connect-core-1_0.html#IDToken there is a prohibition against multiple nonces in a single token.  That being said, the use of nonce in the OpenID spec is bound to an ID token. So it may be good to distinguish the JWT name-space for EAT nonce.

**Comment by laurencelundblade** [comment]
You can't have multiple claims with the same label and the OpenID nonce is a string, so no way to do multiple nonces with what's there.

**Comment by laurencelundblade** [comment]
Fixed by #184
