### ISSUE TITLE
Should ephemeral keys be allowed for signing EAT's?

### ISSUE THREAD

**Issue by gmandyam** [ietf-rats-wg/eat#19]
As per https://mailarchive.ietf.org/arch/msg/rats/d4GYkpwEMmh0VjD3Gmjd1h82Wpc -

> "The EAT is always signed by the attestation key material provisioned by the manufacturer."
>This seems to prevent nested_eat use cases (e.g., cloud workloads with container/VM entities) where the outer EAT is signed with an "ephemeral" attestation key associated with the instance that is itself attested by the inner EAT signed with the AKM.  I suggest removing the sentence.

**Comment by SimonFrost-Arm** [comment]
Given the growing range of use cases for EAT, the alternative to manufacturer provisioned keys may not just be ephemeral keys, but could be keys obtained via an enrollment operation into some service and securely stored e.g. for anonymization reasons or to reflect a set of claims relevant to some service interaction. Agree that the simplest solution here may be to just drop this sentence but consider also whether the rest of the para, starting "In all operating models, the manufacturer provisions some secret attestation key material..." needs revising. I like the idea of a separate security section which could discuss the trust alternatives for the signing key.

**Comment by nedmsmith** [comment]
A stronger definition of what is meant by 'ephemeral' may be required. This relates to Issue 24.

**Comment by laurencelundblade** [comment]
Pretty sure the resolution here is to remove most of the operational and architectural model text so EAT is just claims definitions like CWT and JWT.

Discussion of key material can go in other documents or profiles.

**Comment by SimonFrost-Arm** [comment]
That would be an ideal resolution

**Comment by laurencelundblade** [comment]
This can be closed because this will go into the architecture document and profiles.

**Comment by laurencelundblade** [comment]
Fixed in #129
