### ISSUE TITLE
Manufacturer performing validation -- "should" or "must"

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/eat#2]
Some comments so far in my reading (which is not yet complete):

 The Manufacturer.  The company that made the entity.  This may be a
      chip vendor, a circuit board module vendor or a vendor of finished
      consumer products.

Given that it may be three (or more) entities, and they each have different
agendas, I think that it might be worth being specific about each level.

  In this case the manufacturer should
  perform the verification, because any release of the key material
  would enable a participant other than the entity to create valid
  signed EATs.

s/manufacturer should/manufacturer MUST/

**Comment by nedmsmith** [comment]
We determined that definition of the trusted endpoint would be out of scope for RATS, at least initially. Normative requirements on how to manufacture a RATS device seems to fit the definition of what is out of scope.

**Comment by laurencelundblade** [comment]
We can close this because the section this pertains to will be removed and go into the architecture document. Also as Ned says, normative requirements on how to manufacture are out of scope.

**Comment by laurencelundblade** [comment]
Fixed by #129
