### ISSUE TITLE
Typo issues with -01

### ISSUE THREAD

**Issue by gmandyam** [ietf-rats-wg/eat#20]
They can be addressed in a -02 version.

Sec. 3:  Change ""It also mentions several claims defined by CWT and JWT are  particularly important for EAT." to 'that are particularly important'

Sec. 3:  Correct "* All claims are optional * No claims are mandatory *."  Redundant.

Sec. 3.11:  "Typically, one will be the device-wide EAT that is low to medium  security and another from a Secure Element or similar that is high security.”  Consider changing "Typically" to "For example".

Sec. 3.11:  "The contents of the "eat" claim must be a fully signed, ...".  "eat" claim should be "nested_eat" claim.

**Comment by laurencelundblade** [comment]
I fixed the last two and pushed to GitHub.

I like the first two the way they are.

**Comment by laurencelundblade** [comment]
Update: fixe the first one now that I see the missing "that".

Have created a separate issue for claim optionality: https://github.com/ietf-rats-wg/eat/issues/23
