### ISSUE TITLE
is submod applicable to attestation results?

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/eat#239]
Or is it an aggregation type only usable for Evidence?

This came up in the [presentation of MAA](https://github.com/CCC-Attestation/meetings/blob/main/materials/GregKostal_EAT_in_MAA.pdf) by @gkostal in the Attestation SIG in CCC.

In particular, the question popped up in the context of how to deal with nesting in Attestation Results and whether submods were an applicable primitive there.

It seems that the EAT document currently does not provide very clear guidance for this and it should.

**Comment by laurencelundblade** [comment]
IMO submods can be used in AR or not. Depends on the Verifier policy and what it wants to present to the RP. It's perfectly fine to present a very simple overall "OK" in AR even if the evidence had a dozens submods and it's perfectly fine to present detailed info on each submod in AR.

Some AR profiles will probably prohibit conveying the submods and their details. That is fine too.

Agreed that we can put some guidance in.

**Comment by thomas-fossati** [comment]
Thanks Laurence.  On the call @dthaler suggested that if the job of describing how submods are used in AR is delegated to EAT profiles, that profilers are given some concrete guidance.

**Comment by gkostal** [comment]
@laurencelundblade, the confusion that came up in the CCC discussion isn't whether to include or not include submods.  It was whether a particular "claim set" should be modeled as a submod or included as a top level claim.  

The particular example being discussed was when either an Intel SGX quote or an AMD SEVSNP report link to a set of runtime claims via recording the hash of these claims in the `report data` field, should this claimset be included as a named submod or as a top level claim?

**Comment by laurencelundblade** [comment]
Yes, understood that it was about more than presence/absence.

See #256.

Personally, I can imagine a huge range of uses of submodules both in evidence and in AR. And then people will come up with lots of things none of us anticipate.

I could see maybe having an appendix that gave some ideas and examples if we want to have some detail, but it's a bit hard for me to think what to put in the main normative text other than what I propose.

**Comment by laurencelundblade** [comment]
Addressed in #256
