### ISSUE TITLE
Should there be key usage constraints for attestation?

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/eat#24]
It isn't clear whether an key used for attestation is restricted to signing evidence that is controlled by a trusted environment. The risk of not having constraints is the key may be subject to a confused deputy attack where claims are presented as opaque data that then receive a signature and a verifier presumes the attester made the claims. 

Should it be mandatory for EAT claims to reside within the security perimeter of a trusted environment such as a TEEP TEE / TEEP Agent?

**Comment by laurencelundblade** [comment]
I think we must allow EATs to be generated in any environment, even Android apps, Windows Apps and such. 

Signing key protection requirements are for user case policy documents, certification and such. Probably these should come from organizations like FIDO, GP and TCG, not IETF. 

Similarly, whether the key is used to sign attestation and whether the all the things is signs are as authentic as expected is a policy thing. 

However, I DO think EAT should allow signing and labeling of claims from outside the main protection boundary. This is in the current draft as a "submod". Note that this is not pegging security to any absolute level, just indicating some claims have different security than others.

**Comment by laurencelundblade** [comment]
Where you thinking of defining a new key use type for attestation? That could be in PKIX and/or COSE and/or JSON Web Key.

Alternatively it could be a security recommendation that attestation keys are only used for attestation.

FIDO has this notion of separation. FIDO has some enforcement through its certification program. IETF has no such program, so the best IETF can do is text in the security considerations section.

**Comment by laurencelundblade** [comment]
Attestation might be big enough and important enough to add a key op type for it here in the key op type registry for JWS and COSE https://www.iana.org/assignments/jose/jose.xhtml#web-key-operations but I'm not convinced yet. Unless there is some expression for support for this, I'm going to close this issue.

**Comment by laurencelundblade** [comment]
Closing this since there is no further concern expressed.
