### ISSUE TITLE
Clarify algorithm claim in DEB digest

### ISSUE THREAD

**Issue by gmandyam** [ietf-rats-wg/eat#246]
It is not clear from the existing text that the algorithm can only be drawn from the COSE/JOSE algorithms registry, except for in the profiles section:  see https://datatracker.ietf.org/doc/html/draft-ietf-rats-eat#section-6.2.7.  Even in the context of profiles, only the COSE algorithm registry is mentioned and not the JOSE registry (https://www.iana.org/assignments/jose/jose.xhtml).  As a result, since the algorithm is not specifically to be drawn from one of the existing registries (except for CWT-based profiles of EAT), then the worst-case assumption is that the algorithm could be arbitrary (and arbitrarily weak).  

If the algorithmic identifier from either the COSE or JOSE registries are to be used, then it would be desirable to explicitly define an algorithm claim which would be consistent data types in the CWT/JWT headers respectively.

**Comment by laurencelundblade** [comment]
Fixed in #250
