### ISSUE TITLE
DEB is a poor choice of TLA

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/eat#249]
Using "DEB" to mean Detached EAT Bundle is a very bad conflict.
I was somewhat willing to sit on my hands for this, but now I see it in rats-eat-media-types, and application/eat-deb+cbor is just a disaster.  

3) DEB is a poor choice of a TLA.  ".deb" are Debian packages.
   Attestation is going to get tied up with SBOMs and other things, and the cognitive overload of two TLAs will be a problem.
   I don't think that the TLA helps understanding, I'd just go for Detached EAT.

DEB is used in section 1.2 in the title (which means in the ToC) before it is defined.

eat-deb media type is effective... EAT - Detatched-EAT-Bundle.

   **Also, "DEB" is not used consistently through the document, so maybe you just don't need a TLA here.**

If you do, then I suggest DetB

**Comment by laurencelundblade** [comment]
Fixed by #252
