### ISSUE TITLE
Boot state text corrections:  ver. -01

### ISSUE THREAD

**Issue by gmandyam** [ietf-rats-wg/eat#25]
Sec.'s 3.7.3, 3.7.4 and 3.7.5 start out with the term "this claim".  These are actually not claims as per the definition in Sec. 3.7, but boolean values included in the boot_state claim.

**Comment by laurencelundblade** [comment]
Agreed. Wording should be fixed.

**Comment by laurencelundblade** [comment]
Fixed in #36
