### ISSUE TITLE
Remove Sec. 1.3 EAT Operating Models (ver. -01)

### ISSUE THREAD

**Issue by gmandyam** [ietf-rats-wg/eat#27]
2 reasons:

a) Neither RFC 8392 (CWT) nor RFC 7519 (JWT) have operational models.  Since EAT is derived from these specifications, it would be desirable to maintain consistency.

b) This topic is better covered in an architecture specification.

**Comment by laurencelundblade** [comment]
Can be closed because the plan is to move this to architecture

**Comment by laurencelundblade** [comment]
Fixed in #129
