### ISSUE TITLE
an entity is never a server or a service or a person or organization

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/eat#289]
> 2) s1.1: _An entity is never a server or a service_ I don't want to
    > disagree with this statement, but as a negative statement in a series
    > of positive statements it must be there because it is guarding against
    > some confusion.  I suggest that it be moved to the end of the section,
    > and that it be expanded to explain what the confusion is.  Or that it
    > be removed.

I see that it has been removed, sorta.
The new text is much denser and harder to understand.
I think that the text I complained about has now become:
  _In the EAT context, "entity" never refers to a person or organization._

Again, if we are making negative statements, it is because we are guarding
against some mistake.  Can we state that mistake/confusion?

**Comment by carl-wallace** [comment]
The sentence immediately before the sentence you cite gives the reason. The mistake/confusion that is being addressed is that the term entity has already been defined such that entities may be people or organizations. The sentence in question just says not here. In context, it reads:
```
An entity also corresponds to a "system component", as defined in the Internet Security Glossary [[RFC4949](https://ietf-rats-wg.github.io/eat/draft-ietf-rats-eat.html#RFC4949)]. That glossary also defines "entity" and "system entity" as something that may be a person or organization as well as a system component. In the EAT context, "entity" never refers to a person or organization.
```

**Comment by laurencelundblade** [comment]
This looks fixed in draft-14 to me. (re open if not).
