### ISSUE TITLE
please get Google Android team review of Location Claim

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/eat#292]
> 10) The Location Claim (location) I suggest that we find someone from
    > the Google Android team to review this.  They have specific reasons why
    > they never attest this value, and permit devices to lie about location.

Not addressed.

**Comment by gmandyam** [comment]
a) This was not enumerated as one of the blockers in https://mailarchive.ietf.org/arch/msg/rats/IZbS3lpbN6mfBR4IbeTv60DoaiY/

b)  Strange that only a review is being requested from the "Android team".  Moreover, it seems that an :Android team" review is more important than a WIndows team or IOS team review.  Also note that it is not clear who the "Android team" would be,, and whether their assessment actually represents the Android ecosystem in its entirety.

c)  Couldn't find evidence of a formal Android team review in the Geopriv standards:  see https://mailarchive.ietf.org/arch/browse/geopriv/.  

d) Attested location was reviewed by Google/MS in the context of the Web Authn API L1 (https://www.w3.org/TR/webauthn-1/#sctn-location-extension).  This work preceded the RATS WG efforts.  

e) Could not find where in IETF RFC guidelines where editors are obligated to get formal reviews conducted by vendors of proprietary platforms.  We can re-open this issue if someone can provide a pointer to which IETF guideline requires this.

**Comment by nedmsmith** [comment]
It should be noted that location depends on external entities (satellites) for its values which an Attesting Environment can't be certain are correct (as a jamming attack could alter geo-coordinates). The RATS architecture expects the Attesting Environment is design in such a way that the Target Environment can't lie about the measurement produced. In the case of location claim, these exceptions should be noted.

**Comment by gmandyam** [comment]
>It should be noted that location depends on external entities (satellites) for its values which an Attesting Environment can't be certain are correct (as a jamming attack could alter geo-coordinates).

Such a statement assumes that satellites are the only way to derive location.  Also, this issue was opened with respect to a request from only the "Android team".  The point being raised above should be discussed in a different issue.
