### ISSUE TITLE
IANA considerations, expert review guidance needs clarity

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/eat#296]
Since we are re-using the CWT/JWT claim registry (which I support), we have to live within their expert review boundary.
We can, however, specify additional considerations, or we can allow for easier allocation by reference to this document.

    > 18) Section 9.2 feels like it is amending the IANA Considerations for
    > CWT/JWT Claims.  I think if we had some kind of sub-registry, we would
    > clearly be allowed to do that.  Given how things are, I'm not sure what
    > we can do, but maybe this section should be written more clearly as
    > advice to the Expert Reviews.

No obvious advice has been added.

**Comment by carl-wallace** [comment]
Section 10.2 (in -14 and later) does not amend the IANA Considerations for either CWT or JWT registries. It includes some language stating that EAT claims belong in both with some text to indicate how to handle that. The instructions are for folks registering claims, not for experts reviewing claims. Expert review should be as before. The entirety of [10.2](https://ietf-rats-wg.github.io/eat/draft-ietf-rats-eat.html#name-claims-registered-by-this-d) from the current editor's copy of -15 is below.

```
This specification adds the following values to the "JSON Web Token Claims" registry established by [[RFC7519](https://ietf-rats-wg.github.io/eat/draft-ietf-rats-eat.html#RFC7519)] and the "CBOR Web Token Claims Registry" established by [[RFC8392](https://ietf-rats-wg.github.io/eat/draft-ietf-rats-eat.html#RFC8392)]. Each entry below is an addition to both registries.

The "Claim Description", "Change Controller" and "Specification Documents" are common and equivalent for the JWT and CWT registries. The "Claim Key" and "Claim Value Types(s)" are for the CWT registry only. The "Claim Name" is as defined for the CWT registry, not the JWT registry. The "JWT Claim Name" is equivalent to the "Claim Name" in the JWT registry.
```

**Comment by laurencelundblade** [comment]
Michael's original comment 18) was on draft-13 which had a section 9.2 titled "Claims Characteristics".  Our response to comment 18) has been to move "9.2 Claims Characteristics" to a non-normative appendix in draft-14. Other's have suggested this text wasn't suited for IANA processing (I think IANA themselves). We're not creating a sub-registry so we can't impose new normative expert review criteria.

The "Claims Characteristics" Appendix is framed up a non-normative design guidance. It is not framed up as expert review criteria, but an expert could consider it.

I think the non-normative appendix as a reasonable balance between create a sub-registry for attestation-oriented claims and not providing any comment at all.

So there was definitely a response to Michael's comment 18) and I don't see anything further is necessary.

**Comment by laurencelundblade** [comment]
Close per discussion in London and per request for input on mail list. https://mailarchive.ietf.org/arch/msg/rats/I3oJZdevJ8rVR6pgbeyLvGL80Sw/
