### ISSUE TITLE
some advice on freshness would be good

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/eat#297]
> 20) the Security Considerations section is inadequate.

    > I think that the document should address freshness with reference to
    > the Architecture document.  (no, not in the SC, but the SC needs to
    > refer to it when talking about stale Evidence) It is probably the case
    > that _Implicit Timekeeping using Nonces_ is often the right answer when
    > EAT is transported over TLS.  The nonce can be generated via a TLE
    > Exporter, and I'd like to see this defined.  Since TLS exporters need a
    > string to hash through, that should go into a new section.  I don't
    > think this needs/should be left to the profile.

    > For other freshness mechanisms, the connection to the EAT Nonce perhaps
    > needs to be made very very clear.  Like, hit them over the head.

**Comment by henkbirkholz** [comment]
I am a little surprised by your assertion that
> the epoch claim cannot be used for replay protection althought the RATS architecture says so.

Because the RATS architecture literally states in the first sentence of https://www.ietf.org/archive/id/draft-ietf-rats-architecture-21.html#section-12.3 'Epoch ID-based Attestation' that
> Epoch IDs, described in [Section 10.3](https://www.ietf.org/archive/id/draft-ietf-rats-architecture-21.html#epochfreshness), can be tampered with, replayed, dropped, delayed, and reordered by an attacker.

**Comment by laurencelundblade** [comment]
Agree with Hannes that EAT should offer only nonce and time stamp claims.

Agree with Henk that Epoch IDs can provide freshness, but don't think we need to sort that out here and don't think EAT should define claims to hold epoch IDs. That seems like a good thing to do in an epoch document.

Also agree that EAT needs some better text in security considerations on freshness. Will leave this open until that is settled.

**Comment by gmandyam** [comment]
>Also agree that EAT needs some better text in security considerations on freshness. Will leave this open until that is settled.

We seem to be going in circles here.  There already was some advice in sec cons on the use of nonce in the -14 Transport Security section, but there was a PR proposed to remove this section in its entirety which was just merged:  see https://github.com/ietf-rats-wg/eat/pull/298.  

Perhaps it would be better if only the editors propose PR's, and make them in response to open must-fix issues until the spec is stable.

**Comment by laurencelundblade** [comment]
I don't think -14 addressed freshness well enough. I think the soon-to-be published -15 may do the job, but not sure. It has a new freshness section in security considerations.

Thinking to leave this open until -15 is published and reviewed in relation to this comment (we're working to get -15 out soon (but note that it won't address every open issue)).

**Comment by laurencelundblade** [comment]
Now that EAT-15 is published, please comment on what is says about the nonce and freshness so we can close this out.   Search for "nonce" and "freshness" and read all the found text. It's not very much so its easier to read the text than the diff. We reference RATS architecture and take a less-is-more approach.

**Comment by laurencelundblade** [comment]
Closing as this has been open and advertised for several months and there have been no comments. It has been advertised in person at the IETF 115 meeting, the RATS mailing list and here in GitHub.
