### ISSUE TITLE
Add a claim definition for SW inventory

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/eat#30]
The claim would list SW on the entity. It would probably include name the name and version of each SW component.  This is probably a complicated claim to define.

See also issue #31 

This might include a signer ID like https://tools.ietf.org/html/draft-tschofenig-rats-psa-token-02 does

**Comment by laurencelundblade** [comment]
There was good humming in favor of this in Singapore.

This seems like the obvious choice: https://tools.ietf.org/html/draft-ietf-sacm-coswid-13

I'm planning to make a pull request

**Comment by SimonFrost-Arm** [comment]
Re the use of CoSWID for this claim: beware that on a constrained system CoSWID has considerable structural overhead, especially if the SW module being described is as a result of discovery e.g. a firmware module during measured boot where only minimal information is available to populate the claim. I'm aware there are some discussions underway which would reduce the 'considerable' description I used above but it will need to come down significantly to be workable for this purpose.

**Comment by laurencelundblade** [comment]
Closed with #102
