### ISSUE TITLE
Should spoofed or corrupted location be addressed in the specification?

### ISSUE THREAD

**Issue by gmandyam** [ietf-rats-wg/eat#300]
See discussion in https://github.com/ietf-rats-wg/eat/issues/292.  

The attester may not always have access to a trusted location source.  Even if the attester includes a GNSS engine within its own security boundary, it may not be able to control the external sources of location information (e.g. NTP, satellite info, etc.).  In addition, platform implementations of location may allow for spoofed location.

Most likely non-normative guidance on this could suffice.

**Comment by laurencelundblade** [comment]
I believe #301 is complete enough to merge and that it addresses this issue. Will merge in a day or so unless there are objections.

**Comment by laurencelundblade** [comment]
Addressed by #301
