### ISSUE TITLE
Add a claim definition for SW measurement and/or integrity status

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/eat#31]
This claim would list measurements made on parts of the entity. Typically a measurement is a hash of some region. This may by SW component or it may be more of a run time integrity measuring memory images.

For TEE-based implementations, it is possible to evaluate the measurement on the device and only list the integrity status as a Boolean rather than a measurement. 

See also issue #30

**Comment by nedmsmith** [comment]
The claim should either be a measurement claim or a boolean claim corresponding to some sort of status being asserted. There shouldn't be an assumption that all TEEs work a certain way. The TEE status claim should be discussed separately from this claim IMO.
