### ISSUE TITLE
Add claim to name profile used by the token

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/eat#32]
Profiles are very concrete, use case specific, documents that say which claims are mandatory and which are optional and other.  For example there might be a profile for payments, one for automotive, one for a specific IoT industry and such. This claim would name the profile in use for this token, perhaps with a reference to its defining document. 

This is used in https://tools.ietf.org/html/draft-tschofenig-rats-psa-token-02

**Comment by SimonFrost-Arm** [comment]
Some further background on the profiles document, from the discussions that lead to its inclusion in the PSA token doc.  The intent behind a profile document is that its a (human readable) description of the token. It would normally contain:
 - Details of the token signing
- The list of expected standard EAT claims used
- The list of any Custom claims used
- The status of the claims (optional / mandatory / recommended)
- A full description of the semantic usage of the claims.
- Any information required to perform verification of claims.
- Any expected structure (e.g. submods) that may need to be understood to interpret the token

There is a question on how profiles would be located if not just assumed to be informational to an existing RP/supplier relationship. One possibility might be to form a new IANA registry containing a mapping of profiles names (as used in this claim) to locations. Another might be for this claim structure to either be a text string identifying the document or a URL to the location.

**Comment by laurencelundblade** [comment]
Proposed #86 to address this.

**Comment by laurencelundblade** [comment]
#86 addresses this
