### ISSUE TITLE
Add boot seed claim

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/eat#34]
This is a random value that is generated each time the entity boots. 

https://tools.ietf.org/html/draft-tschofenig-rats-psa-token-02 defines this.

**Comment by nedmsmith** [comment]
It should be clearly documented that the seed value isn't a secret (if that is the case?). If so, then it would be more correct to call it a 'salt' rather than a 'seed'. A seed that seeds a PRNG or a key gen function is a secret since PRNGs have deterministic results given the same seed.

**Comment by laurencelundblade** [comment]
Added in -06 draft. 

Private/public concern of Ned's is clearly addressed.

A fix for the section number for it is coming in the -10 draft.
