### ISSUE TITLE
IANA Considerations

### ISSUE THREAD

**Issue by hannestschofenig** [ietf-rats-wg/eat#357]
The IANA consideration section contains text that will be removed (or corrected) prior publication. I was not sure which part is actually meant to stay in the document and what is removed or modified.

**Comment by laurencelundblade** [comment]
Yes, I believe there's formal markup to indicate this. I will see what can be done.

**Comment by hannestschofenig** [comment]
Just really minor. You might be able to explain it to IANA during the late publication state

**Comment by laurencelundblade** [comment]
Fixed with #362
