### ISSUE TITLE
use rfc2648 for profile identification

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/eat#419]
_(This is just a suggestion that I leave to the discretion of the editors.)_

There's an opportunity to shorten the Constrained Device Standard Profile
identifier using [RFC2648](https://datatracker.ietf.org/doc/rfc2648/) URNs, i.e., using `urn:ietf:rfc:XXXX` rather than `https://www.rfc-editor.org/rfc/rfcXXXX`.

This would remove 21 bytes from the wire per token, which is in line with the "constrained device" scope we are trying to cover here.

**Comment by laurencelundblade** [comment]
Fixed in #420
