### ISSUE TITLE
small typos in examples

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/eat#447]
A couple of small typos in the examples (A.1):

* `/ manifests / 273` should be `/ measurements / 273`
* the made-up CoAP C-F for CoSWID should be replaced by `258` (the assigned C-F)

**Comment by laurencelundblade** [comment]
Fixed by #450 

In this example, the CoSWID is a payload CoSWID, so a manifest, not a measurement. The label is wrong though.
