### ISSUE TITLE
(Signed) CoSWID, (Signed) ISO SWID & SUIT Manifest Claims

### ISSUE THREAD

**Issue by henkbirkholz** [ietf-rats-wg/eat#46]

**Comment by henkbirkholz** [comment]
Proposal:

Write-up for Claim Definitions for inclusion in drat-ietf-rats-eat (OR separate EAT flavor I-D as on option to expedite wglc/adoption process):

At minimum, nine additional CWT/EAT Claims MUST be defined.

1. Unsigned CoSWID Evidence Claim (including corresponding Security Consideration)
2. Signed CoSWID Evidence Claim including corresponding COSE guidance and Security Consideration)
3. Unsigned CoSWID Payload Claim (including at minimum corresponding Security Consideration)
4. Signed CoSWID Payload Claim (including at minimum corresponding COSE guidance and Security Consideration)
5. Unsigned ISO SWID Evidence Claim (including at minimum corresponding Security Consideration)
6. Signed ISO SWID Evidence Claim (including at minimum corresponding NIST SR 8060 guidance and Security Consideration)
7. Unsigned ISO SWID Payload Claim (including at minimum corresponding Security Consideration)
8. Signed ISO SWID Evidence Claim (including at minimum corresponding NIST SR 8060 guidance and Security Consideration), ad
9. SUIT Manifest Claim (potentially signed and including corresponding Security Consideration)

Dave Waltermire and Henk Birkholz discussed this proposal with respect to:

https://mailarchive.ietf.org/arch/msg/sacm/qrliM4reggLvDu0ft9ianypYFLM
and
https://mailarchive.ietf.org/arch/msg/rats/HKUTLMy843rcnhdjnLvnLx9NUuE
respectively.

The proposal includes the notion to avoid blocking or delaying changes to CBOR tag & content-type definitions of corresponding I-D via additions to the EAT Claim Definition set. Therefore expediting related I-D progress and assuring interoperability between SUIT, SACM & RATS at the same time.

**Comment by nedmsmith** [comment]
What is the difference between "Evidence" claims and "Payload" claims?

**Comment by henkbirkholz** [comment]
Both term in the context of *SWID are defined here:

https://tools.ietf.org/html/draft-ietf-sacm-coswid-13#section-2.3

there is an corresponding answer with more details in the rats email list here:

https://mailarchive.ietf.org/arch/msg/rats/kn_fOc0qofTvyKlUvod1BSgpO3o

**Comment by laurencelundblade** [comment]
Addressed with #102
