### ISSUE TITLE
Clarify on seclevel/security-level in example

### ISSUE THREAD

**Issue by gmandyam** [ietf-rats-wg/eat#55]
Re:  https://tools.ietf.org/html/draft-ietf-rats-eat-03#appendix-A.2

'seclevel' is showing up in the example.  Two issues:

a) seclevel is actually security-level in the current doc.

b) For a submod is not providing attestation info in the form of an (endorsed) EAT, is there any value in providing security-level?  If it is there, what entity is performing the security level assessment?

**Comment by laurencelundblade** [comment]
Fixed a). 

b) is the same as #58

**Comment by gmandyam** [comment]
Close and will track via https://github.com/ietf-rats-wg/eat/issues/58
