### ISSUE TITLE
Who assigns the security level of a submodule?

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/eat#58]

**Comment by henkbirkholz** [comment]
My assumption that only the creator of the EAT that includes the nested structure can ultimately in charge of assigning a "security-level" (I am not super happy with that concept to begin with). There can be claims about the... claimed "security level" inside the nested structure itself, of course. But only trust relationships / trust decisions of the EAT creator that embeds these nested structures can provide a basis to convey a notion of trustworthiness here, I think. Thoughts?

**Comment by laurencelundblade** [comment]
security level is removed.
