### ISSUE TITLE
EAT document should say it can be used for Attestation Results

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/eat#63]
https://github.com/ietf-rats-wg/architecture/issues/92 topic 3 has some points about EAT.

Topic 3: EAT. If accurate, I'd like to see a clear acknowledgement that the Verifier may need to act as an Attester for the Relying Party since I'd like to then see specifically how the IETF EAT specification covers this circumstance. In other words, for an EAT that represents an AttestationResult, would the Evidence for the Verifier be embedded or discovered? If embedded, how are submods distinguished for the Verifier's Evidence versus the AttestationResult's embedded claims, including nested EAT's?

**Comment by gkostal** [comment]
@mcr , thanks for opening this issue in EAT based on a portion of an issue I opened against the architecture document.  

I would title this issue ***"EAT guidance on how to share the information used to establish trust of Verifier by a Relying Party?"***

Using the nomenclature of the IETF RATS Architecture document, I believe the following is true:
1. EAT defines the claims used as "Evidence" or "Attestation Results" in the [RATS architecture diagram](https://www.ietf.org/id/draft-ietf-rats-architecture-04.html#name-architectural-overview)
1. The "Verifier" in the RATS architecture can be a separate entity from the Relying Party.  Hence, it's necessary that the Verifier be able to provide information to the Relying Party to establish this trust.  The [Trust Model](https://www.ietf.org/id/draft-ietf-rats-architecture-04.html#name-trust-model) section in the RATS Architecture document discusses this requirement.
1. This information may take the form of "Evidence" describing the Verifier's execution environment, which is distinct from the "Evidence" it analyzes to produce a specific "Attestation Result".

Many (most? all?) "Verifiers" will need to share this trust establishing information with Relying Parties.  A Relying Party may work with more than one "Verifier".  Is it in scope for EAT to give some guidance on how a Verifier shares this information?  If not EAT, is it (or should it be) in scope for any other standardization process?  Left unaddressed, each Verifier will implement an ad-hoc mechanism, leaving Relying Parties unable to trust EAT tokens without first writing vendor specific logic for each Verifier they work with.

**Comment by henkbirkholz** [comment]
I strongly recommend not to mix conceptual messages here. While composite evidence can include attestation results and vice versa, I think that actually makes it even more important to differentiate theses very clearly and consistently. Yes, we need a corresponding definition of Claims for CWT and (CWT Claims Sets maybe) in order to create unified Attestation Results. Alas, if we start to mix many different meanings under the "catch-all" concept that is EAT, it will become harder and harder to figure out what an EAT instance is actually intended to represent and facilitate. Trust in understanding the meaning of an EAT is quite vital to RATS.

**Comment by laurencelundblade** [comment]
Very many EAT claims will be passed through the Verifier to the RP. After all the original EAT design didn't distinguish the Verifier from the RP. It would be silly and confusing to redefine each claim for Results when they are already defined for Evidence.

There will of course be some claims that don't belong in evidence and vice versa. Maybe some claims will have slightly different semantics as Results than as Evidence, but I can't think of anything obvious so far.

We could use Giri's context claim (see #60) to distinguish results from evidence. We'd add a new value to indicate the EAT is Attestation Results. That or we have a new, perhaps mandatory claim, that says whether the EAT (CWT, JWT or UCCS) is Evidence or Results.

**Comment by laurencelundblade** [comment]
This supplants #44

**Comment by laurencelundblade** [comment]
Proposal to address this in #103

**Comment by laurencelundblade** [comment]
Fixed in #103
