### ISSUE TITLE
looking for example of EAT with PCR quote

### ISSUE THREAD

**Issue by mcr** [ietf-rats-wg/eat#64]
It would be good to have a clear example on how to carry a TPM-2 style PCR Quote in as an example of evidence carried by EAT.

**Comment by tomoveu** [comment]
Indeed @mcr . Thank you for rising this issue. Would be great to have an example how a TPM2 Quote fits with EAT or RATS in general. Open-source code that we can see and test.

**Comment by henkbirkholz** [comment]
Hi Dimi, 
with respect to running code, at the moment we decompose TPM structures in https://github.com/Fraunhofer-SIT/charra

The corresponding CBOR items are currently composed according to the following CDDL spec:

https://ietf-rats.github.io/draft-birkholz-rats-reference-interaction-model/draft-birkholz-rats-reference-interaction-model.html#section-appendix.a

The arrays used include label notation for the human reader. These can be used 1:1 as Claim definitions for EAT today (via a nested Claims Set) called tpm2-quote-request and tpm2-quote response, for example.

If there is demand for that, it would be relatively straight forward for us to add corresponding CDDL in the EAT style that  to the I-D. Everything needed is already defined in that section.

**Comment by tomoveu** [comment]
Thanks Henk!

Here is the recording of your explanation on the TPMdev call - [https://developers.tpm.dev/posts/7112151](https://developers.tpm.dev/posts/7112151) Made things very clear.

The link to the document(Appendix A) also helped a lot. What exactly do you think can go in Appendix B as a format regarding TPM2 Quote & EAT?

**Comment by laurencelundblade** [comment]
https://mailarchive.ietf.org/arch/msg/rats/q4yiqt7I6qkk49bwwrkul2u6mFg/
