### ISSUE TITLE
nested token submods should be byte-string wrapped

### ISSUE THREAD

**Issue by laurencelundblade** [ietf-rats-wg/eat#65]
Right now, the second type of submod, the embedding of a full signed EAT token inside surrounding token is "direct".

I think it needs to be wrapped in a byte string to make it reasonable to implement. When decoding the surrounding token, the nested token will be returned as a byte string that can be easily passed to the COSE/CWT/EAT decoder as these will typically take a byte string as input. 

If it is not a byte string, then you have to convince the CBOR decoder to return the CWT Tag as a byte string even though it is not a byte string or the same or related instance of the CBOR decoder used to decode the outside EAT must be used to decode the inside EAT.

No semantics would change. This is only for a practical consideration of the APIs used for decoding CBOR, COSE, CWT and EAT.

**Comment by henkbirkholz** [comment]
I'd like to propose the following contributions that would introduce changes to the current proposal.
 
1.) The current root type is named eat-claims. I'd propose to change that to simply eat. eat-claims implies simply a claims set, I think.
2.) If you really want to include JWT, the nested-token type should look like this:

> nested-token = bstr .cbor eat / b64url

3.) Change the name "Non-token Submodules" to simply "Claims Sets"
4.) Change the name "Nested EAT" to "Token". The nesting is intrinsic anyways and the term submodule does not really add anything - or maybe I am missing some context here? This also allows to "nest" CWT and not only EAT. CWT and EAT can only be differentiated by the composition of their Claims Sets anyways and therefore it is technically possible to use a CWT here already (although not allowed and that has to be checked by the application every time).
5.) In general, I wonder why submod-name is necessary. This way each "unknown" label has to assumed to be a nested token or claims set. That is rather complex to parse on the application layer, isn't it? I propose to use distinct and well-defined labels for CWT and CWT Claims Sets (and if we are really going to do this the JSON equivalents, still not convinced here).

**Comment by laurencelundblade** [comment]
Fixed with #67
