### ISSUE TITLE
Nonce missing from JSON labels

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/eat#75]
There’s a typo in Section 4.3.1: the “nonce” label is missing.

**Comment by thomas-fossati** [comment]
@laurencelundblade [comment on the mailing list](https://mailarchive.ietf.org/arch/msg/rats/DVCR2E_Dozx0JhHz9Pd5w3RdADU/):

The JWT nonce was already in the IANA registry for JWT. I added CDDL for it and note that some of the CDDL in EAT is for things defined elsewhere before there was CDDL.  See this PR #72 .

**Comment by laurencelundblade** [comment]
Closed with merge of #72
