### ISSUE TITLE
JSON:CBOR equivalency

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/eat#76]
The JSON story is nearly OK, except for two things:
* the Submods claim where the JSON:CBOR equivalency is broken by allowing unbounded
int keys in CBOR that can't have an equivalent in JSON;
* the StringOrURI type whose semantics can’t be preserved when transcoding.

(Possibly the former could be addressed by only allowing string labels, the latter by declaring we only deal with strings.)

**Comment by thomas-fossati** [comment]
@laurencelundblade [comment on the mailing list](https://mailarchive.ietf.org/arch/msg/rats/DVCR2E_Dozx0JhHz9Pd5w3RdADU/):

Pushed a fix for StringOrURI to master.

Made submodule names string only as part of this PR #67 . Was thinking that they should only be strings myself.

**Comment by laurencelundblade** [comment]
Also this fix: https://github.com/ietf-rats-wg/eat/commit/c39f92f49675a27aa67ed3ba65143cbfc002c38f
