### ISSUE TITLE
Debug Disable naming considerations

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/eat#79]
Here are a couple of typographic thoughts about Debug Disable claim.

The "disable" in "Debug disable" looks redundant: it'd be better renaming it as just "Debug" or "Debug status”.

A bit more consistent wording wouldn’t hurt too. e.g.:
* "Not disabled" => “enabled” -- this, combined with the above suggestion, would move us from "debug disable not disabled" to a simpler to digest "debug enabled" :-)
* "Permanent disable" => "disabled permanently"
* "Full permanent disable" => "disabled fully and permanently"

**Comment by laurencelundblade** [comment]
Addressed with #82
