### ISSUE TITLE
Add guidance on registration of unused/lightly-used claims

### ISSUE THREAD

**Issue by gmandyam** [ietf-rats-wg/eat#9]
Section 5 contains guidance on the registration of EAT claims using the CWT registry.  There should be suggested guidance to the expert reviewers to avoid registration of claims intended to be used in EAT that will not achieve widespread adoption.

See https://mailarchive.ietf.org/arch/msg/rats/jBCYPK2hly554HGYTXZXa2t_AGw.

**Comment by nedmsmith** [comment]
There needs to be guidance on what "lightly", "wide-spread" and "will be" are intended to portray.

**Comment by gmandyam** [comment]
As per consensus at IETF 105, it was decided that there does not need to be additional guidance on the use of the CWT/JWT registries.  Therefore this issue is closed.
