### ISSUE TITLE
Modify wording for location claim

### ISSUE THREAD

**Issue by gmandyam** [ietf-rats-wg/eat#91]
As per sec. 3.13 of ver. 8:

From Santeri Paavolainen:

"If the device is stationary, the heading is NaN (floating-point not-a-number)."

But heading -- for some devices -- may be accurately determined even when the device is stationary. For example, a directional radio mast (permanent or adjustable orientation) is (at least hopefully) very stationary, but it includes an accurate directional indication.

I would suggest writing this as

"If the device's heading can not be accurately determined, the heading is NaN (floating-point not-a-number)."

I would also point out that many devices may have an initial accurate heading, but it may drift over time if they are stationary even if they can be accurately positioned. For example, a gyrocompass without an orientation reset will lose its accuracy over time (i.e. it will drift, but the drift may be not consistent so in reality its the error that increases). Is there a consideration to include orientation accuracy in a way similar to positional accuracy?

**Comment by laurencelundblade** [comment]
Need to check in on what WGS84 says about this. Consistency with it is critical. Note also that the references to WGS84 are broken, even the Wikipedia ones.

**Comment by laurencelundblade** [comment]
Still haven't figured out where WGS84 is these days, but W3C definitely agrees with the text in the document NOT with the proposed wording. I would like to leave it as is unless some explanation is given for why this should diverge with W3C.
