### ISSUE TITLE
Can UEID change during lifecycle of entity?

### ISSUE THREAD

**Issue by gmandyam** [ietf-rats-wg/eat#98]
Sec. 3.4:  "The UEID should be permanent."

FIDO IoT Device Onboard spec uses GUID for UEID (https://fidoalliance.org/specs/FDO/FIDO-Device-Onboard-RD-v1.0-20201202.html#guid, https://fidoalliance.org/specs/FDO/FIDO-Device-Onboard-RD-v1.0-20201202.html#DevAttnProt).  However, the UEID is only permanent with respect to the lifecycle state of the entity.

Current text is a 'should' requirement, so in one possible reading of the EAT doc the FIDO spec is compliant.  However, a clarification may be in order.

Suggested additional text:  

"In some attestation situations, exposure of the permanent UEID creates an undesirable correlation between subsequent attestations.  In such situations, a temporary UEID of type RAND can be used so long as the EAT recipient can derive the generator of the EAT without the permanent UEID, such as by external mapping to the temporary UEID, or by using a signature with cryptographic indistinguishability.  The same device / entity should use a permanent UEID when such correlation is not an issue."

**Comment by laurencelundblade** [comment]
What about a UEID and an SUEID, where the UEID is permanent and SUEID is semi-permanent? An EAT can have both, one, or the other. The RP use which ever one they want when there are both.

Semi-permanent generally means that the UEID may change when a device changes owners, managers, is factory reset or such. To know exactly when it is reset consult the profile document.

Another privacy solution is to authenticate the RP and generate an RP-specific UEID. That is what Haven Token did.

Others may have other problems with the UEID permanence and maybe other solutions are possible for those other problems.

**Comment by laurencelundblade** [comment]
Coxed by #101
